import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron";
import {
  IPC_CHANNEL,
  IPC_EVENT_CHANNEL,
  IPC_TASK_CHANNEL,
  type PlaybackEvent,
  type TaskEvent,
  type TestcardApi,
} from "../shared/ipc.js";

/**
 * `sources` / `channels` / `playback` are pure request/response: each leaf forwards to
 * `ipcRenderer.invoke(IPC_CHANNEL, "namespace.method", ...args)`. They're spelled out rather
 * than generated by a Proxy because `contextBridge.exposeInMainWorld` copies the API object
 * by walking its own enumerable properties — a Proxy has none, so the bridge silently drops
 * the whole namespace and `window.testcard` never appears.
 *
 * `events` is main-initiated (`webContents.send`), so it's a real subscription. The listener
 * only ever receives the event payload — never the Electron `IpcRendererEvent`.
 *
 * `api` is typed as `TestcardApi`, so a renamed or missing method is a compile error here.
 */
function bind<T>(path: string): T {
  return ((...args: unknown[]) => ipcRenderer.invoke(IPC_CHANNEL, path, ...args)) as T;
}

const api: TestcardApi = {
  sources: {
    list: bind("sources.list"),
    login: bind("sources.login"),
    add: bind("sources.add"),
    update: bind("sources.update"),
    refresh: bind("sources.refresh"),
    remove: bind("sources.remove"),
  },
  channels: {
    listByCategory: bind("channels.listByCategory"),
    countries: bind("channels.countries"),
    search: bind("channels.search"),
    browse: bind("channels.browse"),
    recent: bind("channels.recent"),
    removeFromHistory: bind("channels.removeFromHistory"),
    favourites: bind("channels.favourites"),
    categoryList: bind("channels.categoryList"),
    countryList: bind("channels.countryList"),
    toggleFavourite: bind("channels.toggleFavourite"),
  },
  epg: {
    nowNext: bind("epg.nowNext"),
    window: bind("epg.window"),
  },
  movies: {
    categoryList: bind("movies.categoryList"),
    browse: bind("movies.browse"),
    shelves: bind("movies.shelves"),
    search: bind("movies.search"),
    favourites: bind("movies.favourites"),
    recent: bind("movies.recent"),
    removeFromHistory: bind("movies.removeFromHistory"),
    toggleFavourite: bind("movies.toggleFavourite"),
    details: bind("movies.details"),
  },
  series: {
    categoryList: bind("series.categoryList"),
    browse: bind("series.browse"),
    shelves: bind("series.shelves"),
    search: bind("series.search"),
    favourites: bind("series.favourites"),
    recent: bind("series.recent"),
    removeFromHistory: bind("series.removeFromHistory"),
    toggleFavourite: bind("series.toggleFavourite"),
    episodes: bind("series.episodes"),
  },
  progress: {
    get: bind("progress.get"),
    set: bind("progress.set"),
  },
  playback: {
    play: bind("playback.play"),
    playMovie: bind("playback.playMovie"),
    playEpisode: bind("playback.playEpisode"),
    stop: bind("playback.stop"),
    snapshot: bind("playback.snapshot"),
    channelStep: bind("playback.channelStep"),
    exitPlayer: bind("playback.exitPlayer"),
    seekTo: bind("playback.seekTo"),
    seekBy: bind("playback.seekBy"),
    stepEpisode: bind("playback.stepEpisode"),
    setVideoRegion: bind("playback.setVideoRegion"),
    setVolume: bind("playback.setVolume"),
    setPaused: bind("playback.setPaused"),
    setAspect: bind("playback.setAspect"),
    setSubtitleTrack: bind("playback.setSubtitleTrack"),
    setAudioTrack: bind("playback.setAudioTrack"),
    openInVlc: bind("playback.openInVlc"),
    vlcAvailable: bind("playback.vlcAvailable"),
  },
  view: {
    toggleFullscreen: bind("view.toggleFullscreen"),
    isFullscreen: bind("view.isFullscreen"),
  },
  sync: {
    status: bind("sync.status"),
    signUp: bind("sync.signUp"),
    signIn: bind("sync.signIn"),
    signOut: bind("sync.signOut"),
    reenterPassword: bind("sync.reenterPassword"),
    triggerNow: bind("sync.triggerNow"),
  },
  events: {
    onPlayback(listener: (event: PlaybackEvent) => void): () => void {
      const handler = (_event: IpcRendererEvent, payload: PlaybackEvent) => {
        listener(payload);
      };
      ipcRenderer.on(IPC_EVENT_CHANNEL, handler);
      return () => {
        ipcRenderer.off(IPC_EVENT_CHANNEL, handler);
      };
    },
    onTask(listener: (event: TaskEvent) => void): () => void {
      const handler = (_event: IpcRendererEvent, payload: TaskEvent) => {
        listener(payload);
      };
      ipcRenderer.on(IPC_TASK_CHANNEL, handler);
      return () => {
        ipcRenderer.off(IPC_TASK_CHANNEL, handler);
      };
    },
  },
};

try {
  contextBridge.exposeInMainWorld("testcard", api);
  console.log("[preload] testcard bridge exposed OK");
} catch (error) {
  console.error("[preload] exposeInMainWorld FAILED:", error);
}
