import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron";
import { IPC_CHANNEL, IPC_EVENT_CHANNEL, type PlaybackEvent, type TestcardApi } from "../shared/ipc.js";

/**
 * `sources` / `channels` / `playback` are pure request/response: each leaf forwards to
 * `ipcRenderer.invoke(IPC_CHANNEL, "namespace.method", ...args)`. They're spelled out rather
 * than generated by a Proxy because `contextBridge.exposeInMainWorld` copies the API object
 * by walking its own enumerable properties — a Proxy has none, so the bridge silently drops
 * the whole namespace and `window.testcard` never appears.
 *
 * `events` is main-initiated (`webContents.send`), so it's a real subscription. The listener
 * only ever receives the event payload — never the Electron `IpcRendererEvent`.
 *
 * `api` is typed as `TestcardApi`, so a renamed or missing method is a compile error here.
 */
function bind<T>(path: string): T {
  return ((...args: unknown[]) => ipcRenderer.invoke(IPC_CHANNEL, path, ...args)) as T;
}

const api: TestcardApi = {
  sources: {
    list: bind("sources.list"),
    add: bind("sources.add"),
    refresh: bind("sources.refresh"),
    remove: bind("sources.remove"),
  },
  channels: {
    listByCategory: bind("channels.listByCategory"),
    countries: bind("channels.countries"),
    search: bind("channels.search"),
    browse: bind("channels.browse"),
    recent: bind("channels.recent"),
    favourites: bind("channels.favourites"),
    categoryList: bind("channels.categoryList"),
    countryList: bind("channels.countryList"),
    toggleFavourite: bind("channels.toggleFavourite"),
  },
  playback: {
    play: bind("playback.play"),
    stop: bind("playback.stop"),
    snapshot: bind("playback.snapshot"),
    setVideoRegion: bind("playback.setVideoRegion"),
    setVolume: bind("playback.setVolume"),
    setPaused: bind("playback.setPaused"),
    setSubtitleTrack: bind("playback.setSubtitleTrack"),
    setAudioTrack: bind("playback.setAudioTrack"),
    openInVlc: bind("playback.openInVlc"),
    vlcAvailable: bind("playback.vlcAvailable"),
  },
  overlay: {
    setInteractive: bind("overlay.setInteractive"),
  },
  events: {
    onPlayback(listener: (event: PlaybackEvent) => void): () => void {
      const handler = (_event: IpcRendererEvent, payload: PlaybackEvent) => {
        listener(payload);
      };
      ipcRenderer.on(IPC_EVENT_CHANNEL, handler);
      return () => {
        ipcRenderer.off(IPC_EVENT_CHANNEL, handler);
      };
    },
  },
};

contextBridge.exposeInMainWorld("testcard", api);
