import { dark, light } from "./colors.ts";

const block = (selector: string, vars: Record<string, string | undefined>) =>
  `${selector} {\n${Object.entries(vars).map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n}\n`;

/** The colour half of the stylesheet. Layout, type, motion and the colour-mix tokens live in tokens.css. */
export function cssFor(): string {
  return `/* GENERATED by packages/theme: edit src/colors.ts and run \`pnpm --filter @testcard/theme generate\`. */\n${block(":root", dark)}\n${block(':root[data-theme="light"]', light)}`;
}
