plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(libs.kotlinx.coroutines.core)
    api(libs.kotlinx.serialization.json)
    api(libs.okhttp)
    api(libs.sqlite)
    implementation(libs.sqlite.bundled)
    // XMLTV is read with the platform's pull parser on Android; the JVM tests bring kxml2, which is what Android's is.
    compileOnly(libs.kxml2)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.kxml2)
    testImplementation(libs.okhttp.mockwebserver)
    testRuntimeOnly(libs.junit.platform.launcher)
}

// The vectors are generated by the TypeScript core (packages/core, `pnpm --filter @testcard/core vectors`); every
// Kotlin port must reproduce them. They are read straight from there so there is one copy.
sourceSets.test {
    resources.srcDir("../../../packages/core/test-vectors")
}

tasks.test {
    useJUnitPlatform()
}
